# -*- coding: utf-8 -*-
"""Desktop/Console Application project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VyDaaqbuZYPyyP0_F_etzWUNzscjoYlc
"""

import sqlite3
import matplotlib.pyplot as plt

# Database Setup
conn = sqlite3.connect("expenses.db")
cursor = conn.cursor()
cursor.execute("""
CREATE TABLE IF NOT EXISTS expenses(
    id INTEGER PRIMARY KEY,
    category TEXT,
    amount REAL,
    description TEXT,
    date TEXT
)
""")
conn.commit()

# Add Expense Function
def add_expense(category, amount, description, date):
    cursor.execute("INSERT INTO expenses(category, amount, description, date) VALUES (?, ?, ?, ?)",
                   (category, amount, description, date))
    conn.commit()
    print("Expense Added Successfully!")

# View Expenses
def view_expenses():
    cursor.execute("SELECT * FROM expenses")
    rows = cursor.fetchall()
    for row in rows:
        print(row)

# Generate Category Report
def report_by_category():
    cursor.execute("SELECT category, SUM(amount) FROM expenses GROUP BY category")
    data = cursor.fetchall()
    categories = [x[0] for x in data]
    amounts = [x[1] for x in data]
    plt.pie(amounts, labels=categories, autopct='%1.1f%%')
    plt.title("Expenses by Category")
    plt.show()

# Example Usage
add_expense("Food", 250, "Lunch at cafe", "2026-03-17")
add_expense("Transport", 100, "Taxi ride", "2026-03-17")
view_expenses()
report_by_category()